###### general
fps: 2
annotations: "/nfs/home/arafatj/master_project/annotations/all/"
output_dir: "/nfs/home/arafatj/master_project/OUTPUT/"
######

###### features.py
tmp_dir: "/nfs/home/arafatj/tmp/"
spk_diarization_script: "/nfs/home/arafatj/master_project/whisper-diarization-main/diarize.py"
CLIP_queries: "/nfs/home/arafatj/master_project/models/CLIP/CLIP_queries_v2.json"
places365_architecture: resnet50
places365_model: "/nfs/home/arafatj/master_project/models/Places365/{architecture}_places365.pth.tar"
places365_categories: "/nfs/home/arafatj/master_project/models/Places365/categories_places365.txt"
stopwords: "/nfs/home/arafatj/master_project/models/Topic_Modeling/stopwords.txt"
######

###### create_train_data.py
clip_queries: "/nfs/home/arafatj/master_project/models/CLIP/CLIP_queries.json"
trainingdata_dir: "/nfs/home/arafatj/master_project/trainingdata/"

source_abbreviations:
  - com
  - bild
  - tag

speaker_hierarchy_mapping_0:
  anchor: anchor
  reporter: reporter
  doctor-nurse: other
  expert-medicine: other
  expert-other: other
  layperson: other
  layperson-4-covid: other
  layperson-x-covid: other
  police-frwr: other
  politician-ampel: other
  politician-other: other
  politician-n-de: other
  politician-right: other
  celeb: other

speaker_hierarchy_mapping_1:
  anchor: anchor
  reporter: reporter
  doctor-nurse: expert
  expert-medicine: expert
  expert-other: expert
  layperson: layperson
  layperson-4-covid: layperson
  layperson-x-covid: layperson
  police-frwr: other
  politician-ampel: politician
  politician-other: politician
  politician-n-de: politician
  politician-right: politician
  celeb: other

groundtruth_numerical:
  anchor: 0
  reporter: 1
  other: 2
  expert: 3
  layperson: 4
  politician: 5

labels_0:
  - anchor
  - reporter
  - other

labels_1:
  - anchor
  - reporter
  - other
  - expert
  - layperson
  - politician

window_lengths:
  - 5
  - 10
  - 20
  - 40

delta_t: 2.5
######

###### training.py
speaker_trainingdata_tagesschau_seg: "/nfs/home/arafatj/master_project/trainingdata/speaker/segment_based/hierarchy_{speaker_hierarchy_level}/tag_233_samples_trainingdata.pkl"
speaker_trainingdata_bildtv_seg: "/nfs/home/arafatj/master_project/trainingdata/speaker/segment_based/hierarchy_{speaker_hierarchy_level}/bild_91_samples_trainingdata.pkl"
speaker_trainingdata_compacttv_seg: "/nfs/home/arafatj/master_project/trainingdata/speaker/segment_based/hierarchy_{speaker_hierarchy_level}/com_82_samples_trainingdata.pkl"

speaker_trainingdata_tagesschau_window: "/nfs/home/arafatj/master_project/trainingdata/speaker/window_based/hierarchy_{speaker_hierarchy_level}/tag_233_samples_trainingdata.pkl"
speaker_trainingdata_bildtv_window: "/nfs/home/arafatj/master_project/trainingdata/speaker/window_based/hierarchy_{speaker_hierarchy_level}/bild_91_samples_trainingdata.pkl"
speaker_trainingdata_compacttv_window: "/nfs/home/arafatj/master_project/trainingdata/speaker/window_based/hierarchy_{speaker_hierarchy_level}/com_82_samples_trainingdata.pkl"

k: 5

feature_names:
  - clip_Anchor
  - clip_Reporter
  - clip_PoliceFrwr
  - clip_DoctorNurse
  - clip_Xcov
  - clip_4cov
  - clip_Layperson
  - clip_ExpMedicine
  - clip_ExpOth
  - clip_Polit
  - clip_PolitAmpel
  - clip_PolitRight
  - clip_PolitOther
  - clip_Polit-n-de
  - clip_Celeb
  - clip_Talkinghead
  - clip_Interview
  - clip_Speech
  - clip_Commenting
  - clip_Voiceover
  - clip_Studio
  - clip_Indoor
  - clip_Outdoor
  - Avg_Shotdensity
  - LengthOfSpeech
  - PositiveSentProb
  - NegativeSentProb
  - NeutralSentProb
######

###### utility.py
BildTV_videos: "/nfs/data/fakenarratives/BildTV/videos/"
CompactTV_videos: "/nfs/data/fakenarratives/CompactTV/videos/"
Tagesschau_videos: "/nfs/data/fakenarratives/tagesschau/videos/2022/"
######